version: "3"

services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        restart: always
        image: bapttheo/monitoring-projet-back

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        restart: always
        image: bapttheo/monitoring-projet-front
